// Para requisições com body:
// Content-Type: application/json 
// Pule 1 linha
// {}

// Para requisições com headers: 
// Authorization: "token"

### Pegar todos os usuários
GET http://localhost:3006/users

### Pegar todos os produtos
GET http://localhost:3006/products?title=caixa&order=desc

### Criar usuário.
POST http://localhost:3006/users
Content-Type: application/json

{
    "name": "Joaozin da bicicleta",
    "email": "jao@gmail.com.br",
    "password": "1528963"
}


### CRIAR PRODUTO
POST http://localhost:3006/products
Content-Type: application/json

{
    "name": "Web Cam",
    "price": 220.50,
    "imageUrl": "https://i.picsum.photos/id/0/5616/3744.jpg?hmac=3GAAioiQziMGEtLbfrdbcoenXoWAW-zlyEAMkfEdBzQ"
}


### Registrar compra
POST http://localhost:3006/purchases
Content-Type: application/json

{
    "userId": "a82e5e16-5d6a-43ad-ab9b-7e8aa598c320",
    "productId": "c01f32f9-255c-48e5-93f3-45dcb6481f95",
    "quantity": "2"
}

### buscar compras de um usuário pelo ID .
GET http://localhost:3006/users/a13f486b-8078-4f7f-b859-bb0267783aa7/purchases