// Para requisições com body:
// Content-Type: application/json 
// Pule 1 linha
// {}

// Para requisições com headers: 
// Authorization: "token"

### Pegar todos os usuários
GET http://localhost:3006/users

### Pegar todos os produtos
GET http://localhost:3006/products

### Criar usuário.
POST http://localhost:3006/users
Content-Type: application/json

{
    "name": "Junio Batista da Silva",
    "email": "juniorrox@gmail.com.br",
    "password": "1528253"
}

### CRIAR PRODUTO
POST http://localhost:3006/products
Content-Type: application/json

{
    "name": "Teclado Gamer",
    "price": 215.90,
    "imageUrl": "https://i.picsum.photos/id/0/5616/3744.jpg?hmac=3GAAioiQziMGEtLbfrdbcoenXoWAW-zlyEAMkfEdBzQ"
}


### Registrar compra
POST http://localhost:3006/purchases
Content-Type: application/json

{
    "user_id": "a82e5e16-5d6a-43ad-ab9b-7e8aa598c320",
    "product_id": "27d2b313-b457-4d0e-b85d-f8f6c6e63570",
    "quantity": "2"
}

