### Criar Usuário POST 
POST http://localhost:3003/user/ 
Content-Type: application/json

{
    "name": "Junior Rox da Silva", 
    "email": "éotaldojunin@email.com", 
    "password": "24651384321"
}

//**********************************************************/

### Pegar todos os usuários. 
GET http://localhost:3003/user

//**********************************************************/

### Criar POST 
POST http://localhost:3003/post
Content-Type: application/json

{

    "photo":"www.anyimage.com/eu", 
    "description":"kkkkk estou fazendo um post, mesmo sem ter nada o que falar.", 
    "type": "normal",
    "authorId": "77504dfd-f08f-4155-bb94-c779301533db"
}

//**********************************************************/

### Pegar Post pelo ID. 
GET http://localhost:3003/post/1b8011d2-f0ae-4ca0-f66-5183a5a7f049